[zsh-plugins] refine rime_edit

diff --git a/home/private_dot_config/zsh/plugins/functions/rime_edit b/home/private_dot_config/zsh/plugins/functions/rime_edit
--- a/home/private_dot_config/zsh/plugins/functions/rime_edit
+++ b/home/private_dot_config/zsh/plugins/functions/rime_edit
@@ -2,16 +2,16 @@
 # Deploy Rime configuration and restart input method
 
 emulate -L zsh
-setopt err_return no_unset pipe_fail
+# setopt err_return no_unset pipe_fail
 
 _rime_deploy() {
   local -r log_file=/tmp/rime_deploy.log
   local -r build_dir=${RIME_USER_PATH:?RIME_USER_PATH not set}/build
 
-  if (( ! $+commands[rime_deployer] )); then
+  (( ! ${+commands[rime_deployer]} )) && {
     _zlog error "rime_deployer not found in PATH"
     return 1
-  fi
+  }
 
   case ${GTK_IM_MODULE:-} in
     fcitx)
@@ -51,7 +51,7 @@ _rime_deploy() {
 
 # Edit Rime config and deploy if changed
 # Usage: rime_edit <config_file>
-rime_edit() {
+_rime_edit() {
   local config_file=${1:?missing config file}
 
   if [[ ! -f $config_file ]]; then
@@ -59,19 +59,27 @@ rime_edit() {
     return 1
   fi
 
-  if ! ${EDITOR:?EDITOR not set} -- "$config_file"; then
-    _zlog error "Failed to open editor for ${config_file:t}"
+  (( ! ${+commands[chezmoi]} )) && {
+    _zlog error "Failed to edit ${config_file:t}"
+    _zlog error "chezmoi command was not found."
     return 1
-  fi
+  }
+    
+  ${commands[chezmoi]} edit --apply -- "${config_file}" && {
+    _zlog success "${config_file:t} modified Successfully" 
+  } || {
+    _zlog error "Failed to edit ${config_file:t}, Something wrong with chezmoi_edit function." 
+    return 1
+  }
 
-  if [[ ! -N $config_file ]]; then
+  if [[ -N $config_file ]]; then
+    _zlog info "Configuration changed, deploying Rime…"
+    _rime_deploy || return 1
+    _zlog success "Successfully deployed Rime configuration"
+  else
     _zlog info "No changes detected in ${config_file:t}"
     return 0
   fi
-
-  _zlog warn "Configuration changed, deploying Rime…"
-  _rime_deploy || return 1
-  _zlog success "Successfully deployed Rime configuration"
 }
 
-rime_edit "$@"
+_rime_edit "$@"
